config/routes.rb
Motionmeetup::Application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :archives
  post "/" => "home#signup"
  root :to => "home#index"

  get '/event/:id(.:format)' => "event#show"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@message = Message.new
    @previous_meetups = Archive.published.limit(2).all
    @upcoming_meetup = Archive.unpublished.first
    @events = Event.upcoming
  end

  def signup
    @previous_meetups = Archive.published.limit(2).all
    @upcoming_meetup = Archive.unpublished.first
    @message = Message.new(archive_params)
    @events = Event.upcoming
    if @message.valid?
      mimi = MadMimi.new(ENV["MIMI_USERNAME"], ENV["MIMI_API"])
      mimi.add_to_list(@message.email,'MotionMeetup')
      flash[:notice] = "#{@message.email}, you have successfully signed up!"
    else
      flash[:error] = "Please fill all fields correctly."
    end
    render :index
  end

private
  def archive_params
    params.require(:message).permit(:name, :email, :captcha)
  end
end

app/views/home/_about.html.haml
.content-r.content-d

  / Title
  %h2 About Motion Meetup
  / Border
  .border
  .row
    / Your pic with class "profile"
    .span3
      = image_tag "rm.png", class: "profile"
    .span8
      .row{style: "padding-left: 10px;"}
        .social-icons
          %a.tip{"data-original-title" => "Twitter", :href => "https://twitter.com/rubymotion"}
            %i.icon-twitter
          %a.tip{"data-original-title" => "Linkedin", :href => "https://plus.google.com/communities/101717463357676409782"}
            %i.icon-google-plus
      .row{style: "padding-left: 10px;"}
        %p
          We welcome developers of all levels interested in a free RubyMotion meeting where people can share their ideas and encounter new ones.
        %p
          If you're unfamiliar with what RubyMotion is, I have to wonder how you got here.  Learn
          %a{href: "http://www.RubyMotion.com"} more at the RubyMotion site.
        %p
          We're open to suggestions, guests, and code.  We'd like to allow this community to grow, so if you're looking to fork
          %a{href: "https://github.com/IconoclastLabs/MotionMeetup"} the code for this website
          or if you've got other improvements, what are you waiting for?  Do something cool.
        .clearfix

app/views/home/_archive.html.haml
.content-b.content-d
  %h2 Archive
  .border
  .portfolio
    .row
      .span6.offset1
        Previous Meetups
      .span3.offset1
        Upcoming Meetup
    .row
      .span3.offset1
        - unless @previous_meetups.first.nil?
          = link_to image_tag(@previous_meetups.first.asset.url(:small)), archive_url(@previous_meetups.first), {class: "prettyPhoto[pp_gal]"}
      .span3
        .span3.offset1
        - unless @previous_meetups.second.nil?
          = link_to image_tag(@previous_meetups.second.asset.url(:small)), archive_url(@previous_meetups.second), {class: "prettyPhoto[pp_gal]"}
      .span3.offset1
        - unless @upcoming_meetup.nil?
          = link_to image_tag(@upcoming_meetup.asset.url(:small)), archive_url(@upcoming_meetup), {class: "prettyPhoto[pp_gal]"}

    .row
      .span12
        = link_to "Past Meetup Archives", archives_url

app/views/home/_footer.html.haml
/ Footer
%footer
  .container
    .row
      .span8
        / Copyright info
        %p
          Website Copyright &copy; 
          = Time.now.year 
          %a{:href => "http://www.IconoclastLabs.com"} Iconoclast Labs LLC - 
          RubyMotion its logo are a registered trademark of HipByte SPRL 
          %br
          %a{href: "https://github.com/IconoclastLabs/MotionMeetup"} Fork us on Github
      .span3.offset1
        / Social media icons
        .social
          %a.twitter{:href => "https://twitter.com/rubymotion"}
            %i.icon-twitter
          %a.google-plus{:href => "https://plus.google.com/communities/101717463357676409782"}
            %i.icon-google-plus

app/views/home/_schedule.html.haml
.content-g.content-d
  / Title
  %h2 Meetup Schedule
  Times may changed based on audience and analytics.  Please sign up with our mailing list to remain current.
  / Border
  .border
  / Content
  .resume
    - @events.each do |event|
      .row
        .span3
          %h3
            = event.month_year
          .calendar
            %a{href: "/event/#{event.id}.ics"} iCal Download

        .span8
          .rcontent
            %h4
              = event.title
            %p
              = event.description
            %p
              Special Guest
              %span.skill
                %a{href: "#{event.guest_url}"}
                  = event.guest
      .border
    .row
      .span3
        %h3 To Be Announced
        Sign up ot be notified, when this guest is announced
      .span8
        .rcontent
          %h4 The next one...
          %p
            Please contact us if you'd like to talk!
          %p
            Special Guest
            %span.skill
              %a{href: ""} TBA

app/views/home/_signup.html.haml
.content-y.content-d
  %h2 Sign Up to Get Notifications
  .border
  .contact
    .row
      .span6
        / About form
        %p
          %strong Meetups are announced via RubyMotion Dispatch!
          We're not interested in spamming you (unless we can use canned Spam).  We've teamed up with Infinite Red to make sure every meetup is announced in the RubyMotion Dispatch newsletters.
        %p
          = image_tag "dispatch.png"
        %h3
          %a{href: "http://rubymotiondispatch.com/"}
            Click Here to Sign Up
      .span5
        %h3 How It Works
        / normally where a map would go
        %p
          = image_tag "rubymotion_group.png", style: "float: right;"
          Signing up will get you meetup times as well as general RubyMotion updates each week.
        %p
          On the day of the meetup, chat will be handled via the RubyMotion IRC Channel, and video will be provided via Google Hangout.
        .border
        / Address
        .address
          .row
            .span3
              %address
                %span.color.bold.company
                  24/7 IRC channel #rubymotion
            .span2
              %address
                %span.color.bold.company
                  %a{href: "http://webchat.freenode.net/"} freenode.net

app/views/home/index.html.haml
/ Header
%a#homey{:name => "homey"}
%header
  .container
    .row
      .span12
        / Logo or Name section
        .logo
          = link_to image_tag("logo.png"), root_path
          %p.lsub Monthly Online RubyMotion Meetup
    .row
      .span12
        .flexslider
          %ul.slides
            / Slide #1
            / Each slide should be enclosed inside <li> tag.
            %li
              = image_tag "photos/motion.png"
            / Slide #2
            /%li
            /  .alert.alert-info
            /    %strong Meetup Today!
            /    %p
            /      Check back right before 6pm CDT for the Google Hangout broadcast link.
            /    %p
            /      We'll be in the #rubymotion IRC channel while broadcasting the Hangout and will be reading and responding to questions or discussion going on there as well.
            /  = image_tag "photos/next.png"
            / Slide #3
            /%li
            /  = image_tag "photos/s1.jpg"
            / Slide #4
            /%li
            /  = image_tag "photos/s4.jpg"
            / Slide #5
            /%li
            /  = image_tag "photos/s5.jpg"
            / Slide #6
            /%li
            /  = image_tag "photos/s6.jpg"
            / Slide #7
            /%li
            /  = image_tag "photos/s7.jpg"
    .row
      .span10.offset1
        %h3 Hi,
        %p
          If you're a dev interested in keeping up to date with the ecosystem of RubyMotion, you found the right group.
          MotionMeetup is full of RubyMotion developers of all levels who want to keep up to date with the latest in RubyMotion
          technology, or just want to talk shop with other Ruby coders.
    .row
      .span10.offset2
        <iframe width="560" height="315" src="//www.youtube.com/embed/tfHs1EteF4k" frameborder="0" allowfullscreen></iframe>
/ navigation
.navigation
  .container
    .row
      .span12
        .navs
          / Each navigation link should be enclosed inside "box" class. Note down the markup. I am using jQuery Anchor plugin for sliding navigation (http://www.position-absolute.com/articles/better-html-anchor-a-jquery-script-to-slide-the-scrollbar/).
          / Navigation #1
          .box
            .box-y.box-d
              %a#content-y.anchorLink{:href => "#location"}
                %p.top Sign Up
                %p.bor
                %p.bot Get Notified and How
            .clearfix
          / Navigation #2
          .box
            .box-g.box-d
              %a#content-g.anchorLink{:href => "#location"}
                %p.top Schedule
                %p.bor
                %p.bot The When and Who
            .clearfix
          / Navigation #3
          .box
            .box-b.box-d
              %a#content-b.anchorLink{:href => "#location"}
                %p.top Archive
                %p.bor
                %p.bot Past Meetups
            .clearfix
          / Navigation #4
          .box
            .box-r.box-d
              %a#content-r.anchorLink{:href => "#location"}
                %p.top About
                %p.bor
                %p.bot Wut?
            .clearfix
/ Content
.content
  .container
    .row
      .span12
        / For navigation slider
        %a#location{:name => "location"}
      .span12
        / Each section should be enclosed inside the classes "content-X content-d". Where X denotes the background color.
        / Signup section with red background.
        = render "home/signup"
        / Schedule section with green background.
        = render "home/schedule"
        / Archive section with blue background
        = render "home/archive"
        / About section with yellow background
        = render "home/about"
.top-animation
  .container
    .row
      .span12
        / Sliding "UP" navigation arrow
        .top-goo
          %a.top-go.anchorLink{:href => "#homey"}
            %i.icon-circle-arrow-up
= render "home/footer"