config/routes.rb
Motionmeetup::Application.routes.draw do

  devise_for :users
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :archives
  post "/" => "home#signup"
  root :to => "home#index"

  get '/event/:id(.:format)' => "event#show"
end

app/models/archive.rb
# == Schema Information
#
# Table name: archives
#
#  id                 :integer          primary key
#  name               :string(255)
#  title              :string(255)
#  body               :text
#  publish_at         :timestamp
#  created_at         :timestamp
#  updated_at         :timestamp
#  slug               :string(255)
#  asset_file_name    :string(255)
#  asset_content_type :string(255)
#  asset_file_size    :integer
#  asset_updated_at   :timestamp
#

class Archive < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, :use => :slugged
  attr_accessor :asset, :assets_file_name, :assets_content_type, :assets_file_size, :assets_updated_at

  has_attached_file :asset, :styles => {:thumb => "120x120", :small => "240x240", :large => "640x480"},
    :url => '/uploads/:rails_env/:class/:attachment/:id/:style/:basename.:extension',
    :path => ":rails_root/public/uploads/:rails_env/:class/:attachment/:id/:style/:basename.:extension"
  # add a delete_<asset_name> method:
  attr_accessor :delete_asset
  before_validation { self.asset.clear if self.delete_asset == '1' }
  #after_commit { binding.pry }
  def delete_asset
    return 0
  end
  scope :published, -> { where('publish_at < ?', Time.now.to_date).order('publish_at DESC') }
  scope :unpublished, -> { where('publish_at >= ?', Time.now.to_date).order('publish_at ASC') }

  rails_admin do

    configure :name, :string
    configure :title, :string
    configure :body, :text
    configure :publish_at, :datetime
    configure :slug, :string
    configure :asset, :paperclip
    # Cross-section configuration:
    object_label_method :name     # Name of the method called for pretty printing an *instance* of ModelName
    label 'Archive'              # Name of ModelName (smartly defaults to ActiveRecord's I18n API)
    label_plural 'Archives'      # Same, plural
    weight 0                      # Navigation priority. Bigger is higher.
  # parent OtherModel             # Set parent model for navigation. MyModel will be nested below. OtherModel will be on first position of the dropdown
  # navigation_label              # Sets dropdown entry's name in navigation. Only for parents!

    # Section specific configuration:

    list do
      field :name do
        label "Event"
      end
      #filters [:id, :slug, :name, :publish_at]  # Array of field names which filters should be shown by default in the table header
      # items_per_page 100    # Override default_items_per_page
      # sort_by :id           # Sort column (default is primary key)
      # sort_reverse true     # Sort direction (default is true for primary key, last created first)
    end
    edit do
      group :required  do
        label "Required Fields"

        field :name do
          label "Name"
          help "Name is internally used for admins and for url page slug generation. Users will not explicitly see it."

        end
        field :title do
          label "Title"
          help "Archive Title shown in various headings."
        end
        field :asset do
           label "Graphical Asset"
           help "Optional, but recommended."
        end
        field :body do
          label "Page Body (Markdown)"
          help "HTML can be mixed into the markdown content."
        end
      end
      group :optional do
        label "Optional Fields"
        active false
        field :publish_at do
          label "Publish at"
          help "When 'Publish at' is not nil, the archive will be accessible to the public. Dates in the future will be considered scheduled meetups."
        end
        field :slug do
          label "Custom Slug"
          help "This will be automatically generated from the Name field, but can be overridden as long as it's unique."
        end
      end
    end
    show do
      field :asset do
        label "Graphical Asset"
      end
      field :name do
        label "Name"
      end
      field :title do
        label "Title"

      end
      field :body do
        label "Page Body (Markdown)"

      end
      field :slug do
        label "Custom Slug"
      end
      field :publish_at do
        label "Publish at"
      end
    end
  #     edit do; end
  #     export do; end
  #     # also see the create, update, modal and nested sections, which override edit in specific cases (resp. when creating, updating, modifying from another model in a popup modal or modifying from another model nested form)
  #     # you can override a cross-section field configuration in any section with the same syntax `configure :field_name do ... end`
  #     # using `field` instead of `configure` will exclude all other fields and force the ordering
  # end
  end
end

app/controllers/archives_controller.rb
class ArchivesController < ApplicationController
  layout 'archive'
  before_action :set_archive, only: [:show]

  # GET /archives
  # GET /archives.json
  def index
    @archives = Archive.published
    @future_meetups = Archive.unpublished
  end

  # GET /archives/1
  # GET /archives/1.json
  def show
  end



  private
    # Use callbacks to share common setup or constraints between actions.
    def set_archive
      @archive = Archive.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def archive_params
      params.require(:archive).permit(:name, :title, :body, :publish_at)
    end
end

app/views/archives/index.html.haml
.row
  %h1.span12.separate
    Archives of Past Meetups
.row
  .span12
    %h3
      - @archives.each do |archive|
        = archive.publish_at.stamp('2013-05-22')
        = link_to archive.title, archive
        %p
.row
  %h1.span12.separate
    Future Meetups
.row
  .span12
    %h3
      - @future_meetups.each do |meetup|
        = meetup.publish_at.stamp('2013-05-22')
        = link_to meetup.title, meetup
        %p

app/views/archives/show.html.haml
%p#notice= notice

%ul.breadcrumb
  %li
    = link_to 'Archives', archives_path
    %span.divider /
  %li.active
    = link_to @archive.name, archive_path(@archive)

.row
  .span12.media
    -# Hardcoding the image until I see about why Rails4 and Paperclip are not friends.

    %a.pull-left{href: '#', style: 'padding-right: 3%;'}
      - begin
        = image_tag @archive.asset.url(:small), class: 'media-object img-polaroid'
      - rescue
        = image_tag "archive_photos/default.png", class: 'media-object img-polaroid'

    .media-body
      %h1.media-heading
        = @archive.title
.row
  .span12.media.archive_body
    :markdown
      #{@archive.body}
.row
  .span4.offset4
    - if @archive.publish_at.nil?
      %b This archive is unpublished.
    - elsif @archive.publish_at > Time.zone.now
      %b
        = "This page's content will be updated after #{@archive.publish_at.format_like('May 15th, 2013')}"
    - else
      %b Published on
      = @archive.publish_at.format_like('May 15th, 2013')